
export enum FetchProduct  {
    FETCH_PRODUCT_LOADING="FETCH_PRODUCT_LOADING",
    FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT__ERROR="FETCH_PRODUCT_ERROR"
 }
 export enum AddProduct  {
    ADD_PRODUCT_LOADING="ADD_PRODUCT_LOADING",
    ADD_PRODUCT_SUCCESS="ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR="ADD_PRODUCT_ERROR"
 }
 export enum UpdateProduct {
     UPDATE_PRODUCT_LOADING="UPDATE_PRODUCT_LOADING",
     UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS",
     UPDATE_PRODUCT_ERROR="UPDATE_PRODUCT_ERROR"
 }
 export enum DeleteProduct  {
     DELETE_PRODUCT_LOADING="DELETE_PRODUCT_LOADING",
     DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS",
     DELETE_PRODUCT_ERROR="DELETE_PRODUCT_ERROR"
 }
 
 export enum FetchUsers   {
     FETCH_USERS_LOADING="FETCH_USERS_LOADING",
     FETCH_USERS_SUCCESS="FETCH_USERS_SUCCESS",
     FETCH_USERS_ERROR="FETCH_USERS_ERROR"
 }
 export enum DeleteUser  {
    DELETE_USER_LOADING="DELETE_USER_LOADING",
    DELETE_USER_SUCCESS="DELETE_USER_SUCCESS",
    DELETE_USER_ERROR="DELETE_USER_ERROR"
 }

 export enum FetchOrder{
    FETCH_ORDER_LOADING="FETCH_ORDER_LOADING",
    FETCH_ORDER_SUCCESS="FETCH_ORDER_SUCCESS",
    FETCH_ORDER_ERROR="FETCH_ORDER_ERROR"
 }
 export enum UpdateOrder{
    UPDATE_ORDER_LOADING="UPDATE_ORDER_LOADING",
    UPDATE_ORDER_SUCCESS="UPDATE_ORDER_SUCCESS",
    UPDATE_ORDER_ERROR="UPDATE_ORDER_ERROR"
 }
 
 export enum FetchCarts{
     FETCH_CARTS_LOADING="FETCH_CARTS_LOADING",
     FETCH_CARTS_ERROR="FETCH_CARTS_ERROR",
     FETCH_CARTS_SUCCESS="FETCH_CARTS_CARTS"
 }

