export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const PRODUCTS_INITIALSTATE ='PRODUCTS_INITIALSTATE';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_FILTERED_PRODUCTS = 'ADD_TO_FILTERED_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
